steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/calendar-bot', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/calendar-bot']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'calendar-bot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/calendar-bot'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/calendar-bot'
